development:
  adapter: postgresql
  #encoding: utf8
  database: rsa_development
  pool: 5
  timeout: 5000
  host: localhost
  username: rsa
  password: admin

test:
  adapter: postgresql
  #encoding: utf8
  database: rsa_test
  pool: 5
  timeout: 5000
  host: localhost
  username: rsa
  password: admin

production:
  adapter: postgresql
  #encoding: utf8
  database: rsa_production
  pool: 5
  timeout: 5000
  host: localhost
  username: rsa
  password: admin
